In [1]:
import numpy as np

In [6]:
pythonList = [1, 2, 3, 4,5]
print(pythonList)

[1, 2, 3, 4, 5]


In [5]:
npArr = np.array(pythonList)
print(npArr)
print(type(npArr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
# How much memory is consumed by the list and array?
# Program to verify/validate the space efficiency
# Store 1000 elements in Python List and Numpy Array. Check size of each

import sys # sys is built-in module to getSize

# Create 1000 numbers
s = range(1000)
print(sys.getsizeof(1)*len(s), " bytes")

# Create 1000 numbers in np
s1 = np.arange(1000)
print("Numpy array's item size ", s1.itemsize, " bytes")
print(s1.itemsize * s1.size, " bytes")


28000  bytes
Numpy array's item size  4  bytes
4000  bytes


In [17]:
# Time complexity

# 2 lists in python | Add both | generate a new list
# 2 ndarray in Numpy | Add both | generate a new list

# Time tracking in milliseconds

In [19]:
import time

SIZE = 1000000

# Python lists
L1 = range(SIZE)
L2 = range(SIZE)

# Numpy arrays
N1 = np.arange(SIZE)
N2 = np.arange(SIZE)

start = time.time()
# Add python lists index-wise
result = [(x+y) for x,y in zip(L1, L2)]
end = time.time()
print("Python list operation timings: ", (end-start)*1000, " ms")

start = time.time()
# Add numpy arrays
N_result = N1 + N2
end = time.time()
print("Numpy array list operation timings: ", (end-start)*1000, " ms")

Python list operation timings:  107.77878761291504  ms
Numpy array list operation timings:  2.990245819091797  ms


In [21]:
# 2-d array

x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [22]:
print(x[0][0])
print(x[1][1])

1
4


In [23]:
np.sum(x) # sum of all elements

10

In [24]:
np.sum(x, axis=0) # sum of columns


array([4, 6])

In [25]:
np.sum(x, axis=1) # sum of rows

array([3, 7])

In [31]:
y = np.array([[5,6],[7,8]])

In [32]:
x+y

array([[ 6,  8],
       [10, 12]])

In [33]:
x-y

array([[-4, -4],
       [-4, -4]])

In [34]:
x*y

array([[ 5, 12],
       [21, 32]])

In [35]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [37]:
# Filteration Part-1

a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
bool_idx = a>2
print(a[bool_idx])

[3 4 5 6]


In [43]:
# Filteration Part-2

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [44]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [48]:
# print 1,6,7,11
#print(a[0,2,0,1])
col_index = np.array([0,2,0,1])
print(a[np.arange(4), col_index])


[ 1  6  7 11]


In [49]:
print(a[[0,1,2,3],col_index])

[ 1  6  7 11]


In [50]:
a[:2,1:3]

array([[2, 3],
       [5, 6]])