In [1]:
import numpy as np

In [2]:
#Input array
X=np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]])

#Output
y=np.array([
    [1],
    [1],
    [0]])

In [4]:
print(X.shape)
print(y.shape)

(3, 4)
(3, 1)


In [5]:
# Sigmoid function
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [7]:
# Derivatives of sigmoid
def dervatives_sigmoid(x):
    return x*(1-x)

## Variable initialization

In [8]:
epoch = 5000 # training iterations
lr = 0.1 # Setting Learning rate
inputlayer_neurons = X.shape[1] # number of features in input
hiddenlayer_neurons = 3 # number of hidden layer neurons
output_neurons = 1 # number of neurons at output layer


## Weight and bias initialization

In [9]:
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))
bh = np.random.uniform(size=(1,hiddenlayer_neurons))
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons))
bout = np.random.uniform(size=(1, output_neurons))

## Iterations

In [11]:
for i in range(epoch):
    # Forward propogation
    hidden_layer_input1 = np.dot(X, wh)
    hidden_layer_input = hidden_layer_input1 + bh
    hidden_layer_activations = sigmoid(hidden_layer_input)
    output_layer_input1 = np.dot(hidden_layer_activations, wout)
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input)
    
    # Backward propogation
    E = y - output
    slope_output_layer = dervatives_sigmoid(output)
    slope_hidden_layer = dervatives_sigmoid(hidden_layer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hidden_layer = Error_at_hidden_layer * slope_hidden_layer
    wout += hidden_layer_activations.T.dot(d_output) * lr
    bout += np.sum(d_output, axis=0, keepdims=True) * lr
    wh += X.T.dot(d_hidden_layer) * lr
    bh += np.sum(d_hidden_layer, axis=0, keepdims=True) * lr
    
    print(output)

[[0.91119946]
 [0.91788341]
 [0.89901516]]
[[0.90953131]
 [0.91624628]
 [0.8971147 ]]
[[0.90781946]
 [0.91456435]
 [0.89516557]]
[[0.90606293]
 [0.91283654]
 [0.89316675]]
[[0.90426077]
 [0.91106183]
 [0.89111728]]
[[0.90241207]
 [0.90923916]
 [0.88901619]]
[[0.90051593]
 [0.90736756]
 [0.88686257]]
[[0.8985715 ]
 [0.90544605]
 [0.88465556]]
[[0.89657797]
 [0.9034737 ]
 [0.88239435]]
[[0.89453459]
 [0.90144965]
 [0.88007819]]
[[0.89244067]
 [0.89937307]
 [0.87770641]]
[[0.89029558]
 [0.89724322]
 [0.87527842]]
[[0.88809878]
 [0.89505943]
 [0.87279372]]
[[0.88584982]
 [0.8928211 ]
 [0.87025191]]
[[0.88354834]
 [0.89052775]
 [0.86765271]]
[[0.88119409]
 [0.888179  ]
 [0.86499595]]
[[0.87878695]
 [0.88577459]
 [0.86228162]]
[[0.87632693]
 [0.8833144 ]
 [0.85950983]]
[[0.87381417]
 [0.88079844]
 [0.85668086]]
[[0.87124898]
 [0.87822688]
 [0.85379516]]
[[0.86863182]
 [0.87560006]
 [0.85085335]]
[[0.86596334]
 [0.87291851]
 [0.84785626]]
[[0.86324436]
 [0.87018293]
 [0.84480491]]
[[0.8604759

[[0.86857657]
 [0.81559936]
 [0.27575336]]
[[0.8689588 ]
 [0.81595692]
 [0.27509442]]
[[0.86933919]
 [0.81631328]
 [0.27443857]]
[[0.86971774]
 [0.81666842]
 [0.27378581]]
[[0.87009446]
 [0.81702236]
 [0.27313611]]
[[0.87046936]
 [0.8173751 ]
 [0.27248946]]
[[0.87084246]
 [0.81772664]
 [0.27184584]]
[[0.87121375]
 [0.81807698]
 [0.27120524]]
[[0.87158324]
 [0.81842613]
 [0.27056763]]
[[0.87195095]
 [0.81877409]
 [0.26993301]]
[[0.87231689]
 [0.81912086]
 [0.26930134]]
[[0.87268106]
 [0.81946645]
 [0.26867263]]
[[0.87304348]
 [0.81981085]
 [0.26804684]]
[[0.87340414]
 [0.82015407]
 [0.26742397]]
[[0.87376306]
 [0.82049612]
 [0.26680399]]
[[0.87412026]
 [0.82083699]
 [0.2661869 ]]
[[0.87447573]
 [0.82117669]
 [0.26557267]]
[[0.87482948]
 [0.82151522]
 [0.26496129]]
[[0.87518154]
 [0.82185259]
 [0.26435274]]
[[0.87553189]
 [0.82218879]
 [0.263747  ]]
[[0.87588056]
 [0.82252384]
 [0.26314407]]
[[0.87622755]
 [0.82285773]
 [0.26254392]]
[[0.87657288]
 [0.82319047]
 [0.26194654]]
[[0.8769165

[[0.94737041]
 [0.90404487]
 [0.13259921]]
[[0.9474338 ]
 [0.90413306]
 [0.13247178]]
[[0.94749702]
 [0.90422106]
 [0.13234463]]
[[0.94756008]
 [0.90430888]
 [0.13221779]]
[[0.94762297]
 [0.90439651]
 [0.13209123]]
[[0.9476857 ]
 [0.90448395]
 [0.13196497]]
[[0.94774826]
 [0.90457121]
 [0.13183899]]
[[0.94781067]
 [0.90465829]
 [0.13171331]]
[[0.94787291]
 [0.90474518]
 [0.13158792]]
[[0.94793499]
 [0.90483189]
 [0.13146281]]
[[0.94799691]
 [0.90491842]
 [0.13133799]]
[[0.94805867]
 [0.90500477]
 [0.13121345]]
[[0.94812028]
 [0.90509093]
 [0.1310892 ]]
[[0.94818172]
 [0.90517691]
 [0.13096524]]
[[0.94824301]
 [0.90526272]
 [0.13084155]]
[[0.94830414]
 [0.90534834]
 [0.13071815]]
[[0.94836511]
 [0.90543379]
 [0.13059503]]
[[0.94842593]
 [0.90551905]
 [0.13047219]]
[[0.94848659]
 [0.90560414]
 [0.13034962]]
[[0.94854709]
 [0.90568906]
 [0.13022734]]
[[0.94860744]
 [0.90577379]
 [0.13010533]]
[[0.94866764]
 [0.90585835]
 [0.1299836 ]]
[[0.94872769]
 [0.90594274]
 [0.12986214]]
[[0.9487875

[[0.96435607]
 [0.92950364]
 [0.09676884]]
[[0.96438245]
 [0.92954661]
 [0.09670986]]
[[0.96440878]
 [0.92958951]
 [0.09665096]]
[[0.96443507]
 [0.92963236]
 [0.09659216]]
[[0.96446131]
 [0.92967515]
 [0.09653344]]
[[0.9644875 ]
 [0.92971787]
 [0.09647481]]
[[0.96451365]
 [0.92976053]
 [0.09641627]]
[[0.96453975]
 [0.92980314]
 [0.09635782]]
[[0.96456581]
 [0.92984568]
 [0.09629945]]
[[0.96459183]
 [0.92988816]
 [0.09624118]]
[[0.9646178 ]
 [0.92993058]
 [0.09618299]]
[[0.96464372]
 [0.92997294]
 [0.09612489]]
[[0.9646696 ]
 [0.93001524]
 [0.09606687]]
[[0.96469543]
 [0.93005747]
 [0.09600894]]
[[0.96472123]
 [0.93009965]
 [0.0959511 ]]
[[0.96474697]
 [0.93014177]
 [0.09589335]]
[[0.96477267]
 [0.93018383]
 [0.09583568]]
[[0.96479833]
 [0.93022583]
 [0.09577809]]
[[0.96482395]
 [0.93026777]
 [0.0957206 ]]
[[0.96484952]
 [0.93030965]
 [0.09566318]]
[[0.96487504]
 [0.93035147]
 [0.09560586]]
[[0.96490052]
 [0.93039323]
 [0.09554862]]
[[0.96492596]
 [0.93043493]
 [0.09549146]]
[[0.9649513

[[0.97312332]
 [0.94458673]
 [0.07629942]]
[[0.97313659]
 [0.94461091]
 [0.07626691]]
[[0.97314984]
 [0.94463507]
 [0.07623443]]
[[0.97316307]
 [0.9446592 ]
 [0.07620199]]
[[0.97317628]
 [0.94468331]
 [0.07616958]]
[[0.97318948]
 [0.94470739]
 [0.0761372 ]]
[[0.97320266]
 [0.94473145]
 [0.07610486]]
[[0.97321583]
 [0.94475548]
 [0.07607256]]
[[0.97322897]
 [0.94477948]
 [0.07604029]]
[[0.97324211]
 [0.94480346]
 [0.07600805]]
[[0.97325522]
 [0.94482741]
 [0.07597585]]
[[0.97326832]
 [0.94485134]
 [0.07594369]]
[[0.97328141]
 [0.94487524]
 [0.07591156]]
[[0.97329447]
 [0.94489912]
 [0.07587946]]
[[0.97330753]
 [0.94492298]
 [0.0758474 ]]
[[0.97332056]
 [0.9449468 ]
 [0.07581537]]
[[0.97333358]
 [0.94497061]
 [0.07578338]]
[[0.97334658]
 [0.94499439]
 [0.07575142]]
[[0.97335957]
 [0.94501814]
 [0.07571949]]
[[0.97337254]
 [0.94504187]
 [0.0756876 ]]
[[0.97338549]
 [0.94506557]
 [0.07565574]]
[[0.97339843]
 [0.94508925]
 [0.07562392]]
[[0.97341135]
 [0.9451129 ]
 [0.07559213]]
[[0.9734242

 [0.06490818]]
[[0.97763766]
 [0.95309711]
 [0.06488667]]
[[0.97764588]
 [0.95311315]
 [0.06486519]]
[[0.9776541 ]
 [0.95312918]
 [0.06484372]]
[[0.97766231]
 [0.95314519]
 [0.06482227]]
[[0.97767051]
 [0.9531612 ]
 [0.06480084]]
[[0.9776787 ]
 [0.95317718]
 [0.06477943]]
[[0.97768688]
 [0.95319316]
 [0.06475804]]
[[0.97769506]
 [0.95320912]
 [0.06473666]]
[[0.97770323]
 [0.95322507]
 [0.0647153 ]]
[[0.97771139]
 [0.953241  ]
 [0.06469396]]
[[0.97771954]
 [0.95325692]
 [0.06467264]]
[[0.97772769]
 [0.95327283]
 [0.06465134]]
[[0.97773582]
 [0.95328872]
 [0.06463006]]
[[0.97774395]
 [0.9533046 ]
 [0.06460879]]
[[0.97775207]
 [0.95332047]
 [0.06458754]]
[[0.97776018]
 [0.95333632]
 [0.06456631]]
[[0.97776829]
 [0.95335216]
 [0.0645451 ]]
[[0.97777639]
 [0.95336798]
 [0.0645239 ]]
[[0.97778448]
 [0.9533838 ]
 [0.06450273]]
[[0.97779256]
 [0.95339959]
 [0.06448157]]
[[0.97780063]
 [0.95341538]
 [0.06446043]]
[[0.97780869]
 [0.95343115]
 [0.0644393 ]]
[[0.97781675]
 [0.95344691]
 [0.0644182

 [0.05612126]]
[[0.98091088]
 [0.95964684]
 [0.05610653]]
[[0.98091621]
 [0.95965779]
 [0.05609181]]
[[0.98092155]
 [0.95966874]
 [0.05607711]]
[[0.98092688]
 [0.95967968]
 [0.05606241]]
[[0.9809322 ]
 [0.95969062]
 [0.05604773]]
[[0.98093753]
 [0.95970154]
 [0.05603305]]
[[0.98094284]
 [0.95971246]
 [0.05601839]]
[[0.98094816]
 [0.95972337]
 [0.05600373]]
[[0.98095347]
 [0.95973428]
 [0.05598908]]
[[0.98095877]
 [0.95974517]
 [0.05597445]]
[[0.98096407]
 [0.95975606]
 [0.05595982]]
[[0.98096937]
 [0.95976694]
 [0.05594521]]
[[0.98097466]
 [0.95977781]
 [0.0559306 ]]
[[0.98097995]
 [0.95978868]
 [0.05591601]]
[[0.98098523]
 [0.95979954]
 [0.05590142]]
[[0.98099051]
 [0.95981039]
 [0.05588685]]
[[0.98099579]
 [0.95982123]
 [0.05587228]]
[[0.98100106]
 [0.95983206]
 [0.05585773]]
[[0.98100633]
 [0.95984289]
 [0.05584318]]
[[0.9810116 ]
 [0.95985371]
 [0.05582864]]
[[0.98101685]
 [0.95986452]
 [0.05581412]]
[[0.98102211]
 [0.95987533]
 [0.0557996 ]]
[[0.98102736]
 [0.95988613]
 [0.0557851

 [0.05100719]]
[[0.9827354 ]
 [0.96344398]
 [0.05099575]]
[[0.98273942]
 [0.96345245]
 [0.05098431]]
[[0.98274343]
 [0.96346092]
 [0.05097288]]
[[0.98274744]
 [0.96346939]
 [0.05096146]]
[[0.98275145]
 [0.96347785]
 [0.05095004]]
[[0.98275546]
 [0.9634863 ]
 [0.05093864]]
[[0.98275946]
 [0.96349475]
 [0.05092724]]
[[0.98276346]
 [0.96350319]
 [0.05091584]]
[[0.98276746]
 [0.96351163]
 [0.05090445]]
[[0.98277146]
 [0.96352007]
 [0.05089307]]
[[0.98277545]
 [0.9635285 ]
 [0.0508817 ]]
[[0.98277944]
 [0.96353692]
 [0.05087033]]
[[0.98278343]
 [0.96354534]
 [0.05085897]]
[[0.98278741]
 [0.96355375]
 [0.05084761]]
[[0.98279139]
 [0.96356216]
 [0.05083627]]
[[0.98279537]
 [0.96357057]
 [0.05082493]]
[[0.98279935]
 [0.96357896]
 [0.05081359]]
[[0.98280333]
 [0.96358736]
 [0.05080226]]
[[0.9828073 ]
 [0.96359575]
 [0.05079094]]
[[0.98281127]
 [0.96360413]
 [0.05077963]]
[[0.98281523]
 [0.96361251]
 [0.05076832]]
[[0.9828192 ]
 [0.96362088]
 [0.05075702]]
[[0.98282316]
 [0.96362925]
 [0.0507457

[[0.98437237]
 [0.96693837]
 [0.04626708]]
[[0.98437538]
 [0.96694487]
 [0.04625826]]
[[0.98437839]
 [0.96695136]
 [0.04624945]]
[[0.98438139]
 [0.96695785]
 [0.04624064]]
[[0.98438439]
 [0.96696433]
 [0.04623184]]
[[0.9843874 ]
 [0.96697081]
 [0.04622304]]
[[0.9843904 ]
 [0.96697729]
 [0.04621424]]
[[0.98439339]
 [0.96698376]
 [0.04620545]]
[[0.98439639]
 [0.96699024]
 [0.04619667]]
[[0.98439938]
 [0.9669967 ]
 [0.04618788]]
[[0.98440238]
 [0.96700317]
 [0.04617911]]
[[0.98440537]
 [0.96700963]
 [0.04617034]]
[[0.98440836]
 [0.96701609]
 [0.04616157]]
[[0.98441135]
 [0.96702254]
 [0.0461528 ]]
[[0.98441433]
 [0.96702899]
 [0.04614404]]
[[0.98441732]
 [0.96703544]
 [0.04613529]]
[[0.9844203 ]
 [0.96704188]
 [0.04612654]]
[[0.98442328]
 [0.96704832]
 [0.04611779]]
[[0.98442626]
 [0.96705476]
 [0.04610905]]
[[0.98442924]
 [0.96706119]
 [0.04610032]]
[[0.98443221]
 [0.96706762]
 [0.04609158]]
[[0.98443519]
 [0.96707405]
 [0.04608286]]
[[0.98443816]
 [0.96708047]
 [0.04607413]]
[[0.9844411

[[0.98552441]
 [0.96944413]
 [0.04285609]]
[[0.98552681]
 [0.96944938]
 [0.04284892]]
[[0.9855292 ]
 [0.96945463]
 [0.04284175]]
[[0.9855316 ]
 [0.96945988]
 [0.04283459]]
[[0.98553399]
 [0.96946512]
 [0.04282742]]
[[0.98553639]
 [0.96947037]
 [0.04282027]]
[[0.98553878]
 [0.96947561]
 [0.04281311]]
[[0.98554117]
 [0.96948085]
 [0.04280596]]
[[0.98554356]
 [0.96948608]
 [0.04279881]]
[[0.98554595]
 [0.96949131]
 [0.04279167]]
[[0.98554834]
 [0.96949655]
 [0.04278453]]
[[0.98555072]
 [0.96950177]
 [0.04277739]]
[[0.98555311]
 [0.969507  ]
 [0.04277025]]
[[0.98555549]
 [0.96951222]
 [0.04276312]]
[[0.98555787]
 [0.96951744]
 [0.04275599]]
[[0.98556025]
 [0.96952266]
 [0.04274887]]
[[0.98556263]
 [0.96952788]
 [0.04274174]]
[[0.98556501]
 [0.96953309]
 [0.04273463]]
[[0.98556739]
 [0.9695383 ]
 [0.04272751]]
[[0.98556977]
 [0.96954351]
 [0.0427204 ]]
[[0.98557214]
 [0.96954872]
 [0.04271329]]
[[0.98557452]
 [0.96955392]
 [0.04270618]]
[[0.98557689]
 [0.96955913]
 [0.04269908]]
[[0.9855792

[[0.98649823]
 [0.97158916]
 [0.03991999]]
[[0.98650017]
 [0.97159347]
 [0.03991408]]
[[0.98650212]
 [0.97159777]
 [0.03990817]]
[[0.98650406]
 [0.97160208]
 [0.03990226]]
[[0.986506  ]
 [0.97160638]
 [0.03989636]]
[[0.98650794]
 [0.97161068]
 [0.03989046]]
[[0.98650988]
 [0.97161497]
 [0.03988456]]
[[0.98651182]
 [0.97161927]
 [0.03987866]]
[[0.98651376]
 [0.97162356]
 [0.03987277]]
[[0.9865157 ]
 [0.97162786]
 [0.03986688]]
[[0.98651764]
 [0.97163215]
 [0.03986099]]
[[0.98651957]
 [0.97163644]
 [0.0398551 ]]
[[0.98652151]
 [0.97164072]
 [0.03984921]]
[[0.98652345]
 [0.97164501]
 [0.03984333]]
[[0.98652538]
 [0.97164929]
 [0.03983745]]
[[0.98652731]
 [0.97165357]
 [0.03983157]]
[[0.98652924]
 [0.97165785]
 [0.0398257 ]]
[[0.98653118]
 [0.97166213]
 [0.03981982]]
[[0.98653311]
 [0.97166641]
 [0.03981395]]
[[0.98653504]
 [0.97167068]
 [0.03980808]]
[[0.98653697]
 [0.97167496]
 [0.03980222]]
[[0.98653889]
 [0.97167923]
 [0.03979635]]
[[0.98654082]
 [0.9716835 ]
 [0.03979049]]
[[0.9865427

[[0.98724392]
 [0.97324624]
 [0.03764037]]
[[0.98724556]
 [0.97324989]
 [0.03763534]]
[[0.9872472 ]
 [0.97325354]
 [0.03763031]]
[[0.98724883]
 [0.97325719]
 [0.03762528]]
[[0.98725047]
 [0.97326083]
 [0.03762026]]
[[0.9872521 ]
 [0.97326448]
 [0.03761523]]
[[0.98725373]
 [0.97326812]
 [0.03761021]]
[[0.98725537]
 [0.97327176]
 [0.03760519]]
[[0.987257  ]
 [0.9732754 ]
 [0.03760017]]
[[0.98725863]
 [0.97327904]
 [0.03759516]]
[[0.98726026]
 [0.97328267]
 [0.03759014]]
[[0.98726189]
 [0.97328631]
 [0.03758513]]
[[0.98726352]
 [0.97328994]
 [0.03758012]]
[[0.98726515]
 [0.97329358]
 [0.03757511]]
[[0.98726678]
 [0.97329721]
 [0.0375701 ]]
[[0.9872684 ]
 [0.97330084]
 [0.03756509]]
[[0.98727003]
 [0.97330446]
 [0.03756009]]
[[0.98727166]
 [0.97330809]
 [0.03755509]]
[[0.98727328]
 [0.97331172]
 [0.03755009]]
[[0.98727491]
 [0.97331534]
 [0.03754509]]
[[0.98727653]
 [0.97331896]
 [0.03754009]]
[[0.98727816]
 [0.97332259]
 [0.0375351 ]]
[[0.98727978]
 [0.97332621]
 [0.0375301 ]]
[[0.9872814