In [1]:
import numpy as np

In [2]:
X = np.array([1,2,3])
print(X)

[1 2 3]


In [3]:
type(X)

numpy.ndarray

In [4]:
l = [4, 3, 2]
X = np.asarray(l)
print(X)

[4 3 2]


In [5]:
X = np.asarray(l, float)
print(X)

[4. 3. 2.]


In [6]:
X.shape

(3,)

In [7]:
np.array?

In [8]:
X = np.array([[1,2,3],[4,5,6]])

In [9]:
print(X)

[[1 2 3]
 [4 5 6]]


In [10]:
type(X)

numpy.ndarray

In [11]:
X.shape

(2, 3)

In [12]:
X[0,:]

array([1, 2, 3])

In [13]:
X[0,]

array([1, 2, 3])

In [15]:
X[:,0]

array([1, 4])

In [16]:
X = np.zeros((3,4))

In [17]:
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
X = np.eye(2,2)

print(X)

[[1. 0.]
 [0. 1.]]


In [20]:
X = np.random.random((3, 2))
print(X)

[[0.93870824 0.97833396]
 [0.97772641 0.8889212 ]
 [0.80548135 0.9667767 ]]


In [21]:
Z = X.T
print(Z)

[[0.93870824 0.97772641 0.80548135]
 [0.97833396 0.8889212  0.9667767 ]]


In [22]:
Y = X.reshape(6,1)

In [23]:
print(Y)

[[0.93870824]
 [0.97833396]
 [0.97772641]
 [0.8889212 ]
 [0.80548135]
 [0.9667767 ]]


In [24]:
Y = X.reshape(1,6)

In [25]:
A = np.arange(4)
print(A)

[0 1 2 3]


In [26]:
B = np.arange(4)

In [27]:
A+B

array([0, 2, 4, 6])

In [28]:
A-B

array([0, 0, 0, 0])

In [29]:
A*B

array([0, 1, 4, 9])

In [30]:
A+1

array([1, 2, 3, 4])

In [32]:
u = [1, 2, 3]
v = [-1, 0, 1]

p = np.inner(u, v)
print(p)

2


In [33]:
p = np.outer(u, v)
print(p)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [36]:
A = np.ones((2, 3))
B = np.random.random((3, 2))
np.dot(A, B)

array([[2.17579326, 1.42886095],
       [2.17579326, 1.42886095]])

In [37]:
A.sum()

6.0

In [38]:
A.sum(axis=0)

array([2., 2., 2.])

In [39]:
A.sum(axis=1)

array([3., 3.])